### ISSUE TITLE
Only first iteration of subtest has logs in pycharm

### ISSUE THREAD

**Issue by Arroheim** [pytest-dev/pytest-subtests#102]
I am running this code in pycharm:
```python
import logging
import random

logger = logging.getLogger(__name__)


class TestSub:
    def test_has_nested(self, subtests):
        for i in range(5):
            with subtests.test(f"Text - {i}"):
                logger.info(f"This is log for iteration: {i}")
                assert random.choice([True, False])
```

Expect result: Every 5 subtests has logs in "Run" panel
![image](https://github.com/pytest-dev/pytest-subtests/assets/24206337/a50ace97-acaa-4491-b34f-570b7fc7269b)

Actual result: Only first subtest has logs, rest subtests are empty
![image](https://github.com/pytest-dev/pytest-subtests/assets/24206337/07c35d31-03e9-4332-9191-281bcf24306c)

**Comment by nicoddemus** [comment]
Hi @Arroheim,

pytest-subtests will call the [pytest_report_teststatus](https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_report_teststatus) more than once for the `call` phase, I suspect PyCharm does not handle that properly (given that plain pytest only calls that once for the `call` phase). 

I suggest opening an issue on PyCharm's issue tracker, as there is nothing actionable for pytest-subtests.
