### ISSUE TITLE
Publish with `py.typed`

### ISSUE THREAD

**Issue by edgarrmondragon** [pytest-dev/pytest-subtests#114]
https://peps.python.org/pep-0561/

**Comment by nicoddemus** [comment]
hI @edgarrmondragon,

Currently we don't use type annotations in this plugin. You want the types exported so you can type-annotate the `subtests` fixture?

**Comment by edgarrmondragon** [comment]
Hi @nicoddemus!

> Currently we don't use type annotations in this plugin.

I see, didn't notice that! Would you be interested in a PR adding type annotations and a corresponding mypy check for this project?

> You want the types exported so you can type-annotate the `subtests` fixture?

That's exactly right 😄

**Comment by nicoddemus** [comment]
Sure, would love to review a PR in that direction. 👍
