### ISSUE TITLE
Request: adding `SubTests` to `__init__.py`

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest-subtests#121]
I `pip install`ed https://github.com/pytest-dev/pytest-subtests/tree/c1b90cbe4797bc15f83decc74033a6550fa23462, which gives `pytest-subtests==0.11.1.dev18+gc1b90cb`. With this file:

```python
from pytest_subtests import SubTests
```

`mypy` complains, despite https://github.com/pytest-dev/pytest-subtests/issues/114 being closed:

```none
"pytest_subtests": module is installed, but missing library stubs or py.typed
marker  [import-untyped]
    from pytest_subtests import SubTests
    ^
```

Can we add `from .plugin import SubTests` to `__init__.py`?

**Comment by nicoddemus** [comment]
Thanks @jamesbraza! `0.12.0` is out. 🎉

**Comment by jamesbraza** [comment]
@nicoddemus thanks for cutting a release 👍 appreciated

It looks like 0.12.0 got published: https://pypi.org/project/pytest-subtests/0.12.0/

But sadly it's not showing up in the general PyPI page: https://pypi.org/project/pytest-subtests/

Any ideas as to why that might happen?

**Comment by nicoddemus** [comment]
It is probably just not updated yet, it shows up for me just fine:

![image](https://github.com/pytest-dev/pytest-subtests/assets/1085180/85f8c6d0-e299-4308-9cdc-5bfe9c917d7e)


Try CTRL+F5 on your browser.
