### ISSUE TITLE
Require pytest version >= 7.4 or remove dependency on it

### ISSUE THREAD

**Issue by DevonFulcher** [pytest-dev/pytest-subtests#159]
[This](https://github.com/pytest-dev/pytest-subtests/blob/main/src/pytest_subtests/plugin.py#L245) line relies on pytest version 7.4. `from_exception` doesn't exist in version [7.3](https://github.com/pytest-dev/pytest/blob/7.3.x/src/_pytest/_code/code.py#L449) and it was introduced in version [7.4](https://github.com/pytest-dev/pytest/blob/7.4.x/src/_pytest/_code/code.py#L470). This dependency should be removed or the requirements should be updated [here](https://github.com/pytest-dev/pytest-subtests/blob/main/setup.cfg#L31).

**Comment by nicoddemus** [comment]
Thanks!
