### ISSUE TITLE
Question: subtests and pytest-xdist

### ISSUE THREAD

**Issue by liiight** [pytest-dev/pytest-subtests#16]
I have started using subtests and I'm loving it. Would it be possible (and feasible) to make subtest work with xdist in order to parallelize the test executions?

**Comment by RonnyPfannschmidt** [comment]
subtests are part of a code flow that cannot be parallelized by xdist
if your workload is parallelizable however, thats a indication that you might be better served with parametrize  (which generates normal tests  that can be parallelized)

**Comment by liiight** [comment]
True, but what I liked about using subtests as opposed to dynamically needing to parameterize via the `pytest_generate_tests` hook in my case, is the ability to reuse my existing fixture.

The scope separation between code that can be used in hooks and code that can be used in tests is sometimes uncomfortable.

**Comment by RonnyPfannschmidt** [comment]
That is a common unfulfilled need, unfortunately it's not going to be fixed soon

**Comment by liiight** [comment]
I understand. Thanks for the response
