### ISSUE TITLE
Passing StrEnum obj as msg causes serialization error in pytest-xdist

### ISSUE THREAD

**Issue by yugokato** [pytest-dev/pytest-subtests#170]
Here is the minimum code to reproduce the issue:

```
from enum import StrEnum, auto

import pytest
from pytest_subtests import SubTests


class MyEnum(StrEnum):
    FOO = auto()


@pytest.mark.parametrize("p", range(2))
def test_something(subtests: SubTests, p):
    with subtests.test(MyEnum.FOO):
        pass

```

Running the above test with `pytest-xdist` (with `-n 2`, for example)  results in the following error:

```
self = <execnet.gateway_base._Serializer object at 0x105c4d760>, obj = <MyEnum.FOO: 'foo'>

    def _save(self, obj: object) -> None:
        tp = type(obj)
        try:
            dispatch = self._dispatch[tp]
        except KeyError:
            methodname = "save_" + tp.__name__
            meth: Callable[[_Serializer, object], None] | None = getattr(
                self.__class__, methodname, None
            )
            if meth is None:
>               raise DumpError(f"can't serialize {tp}") from None
E               execnet.gateway_base.DumpError: can't serialize <enum 'MyEnum'>
```

I expected this to work as the value I passed is technically a string (`MyEnum.FOO` is of type `str`).

NOTE:  I'm actually not sure if this should be handled by pytest-xdist (execnet) or pytest-subtests. I decided to open it as a pytest-subtests issue after seeing [this comment](https://github.com/pytest-dev/pytest-xdist/issues/1157#issuecomment-2492553944).

### Environment
- Python 3.12
- pytest==8.3.4
- pytest-subtests==0.13.1
- pytest-xdist==3.6.1

**Comment by nicoddemus** [comment]
Thanks for the report, but this is actually related to xdist, as it is trying to serialize and send the object to the gateway. 👍

**Comment by yugokato** [comment]
Will open this in pytest-xdist
