### ISSUE TITLE
Show count of subtests in summary

### ISSUE THREAD

**Issue by reaperhulk** [pytest-dev/pytest-subtests#39]
As always, thanks for the work on this extremely useful plugin!

It would be useful if `pytest-subtests` could provide a count of the number of subtests. Either by incrementing the `pytest` test count, or augmenting it with a new section. Something like `2760 passed  (53,383 subtests), 3253 skipped`.

**Comment by nicoddemus** [comment]
Hi @reaperhulk,

Sorry for the delay, missed the notification for this issue.

Indeed a new section would be nice to have. Thanks!

**Comment by reaperhulk** [comment]
@nicoddemus not a problem, I just wanted to file this as a tracking issue for anyone who might have the inclination to implement it. That might be me, but not just yet 😄 (Although if you have any pointers on where in pytest this might best be tracked that could be helpful!)

**Comment by reaperhulk** [comment]
@nicoddemus I was looking at this again recently and I'm curious why you chose to exclude passed subtests from the summary here: https://github.com/pytest-dev/pytest-subtests/blob/7991ee27c8c31151d3e7a96f5dbac3956ea52d4e/pytest_subtests.py#L38-L39
For my purposes just having this be true for passed would be a major improvement in the final output.

That said, it wouldn't technically be entirely correct, as a test like
```python
def test_thing(subtests):
    for _ in range(5):
        with subtests.test():
            assert True
```
would say 6 passed, the parent test (which does effectively nothing) and the subtests. If that's an issue we want to tackle then the above solution doesn't work and as far as I can tell we have two options:
1) Generate our own subtest count line with `pytest_terminal_summary` (including shell coloring, etc if we want it)
2) Modify `pytest` itself to allow for new types to be added so that `_build_normal_summary_stats_line` can add a `n subtests` section like passed, failed, xfailed, etc.

Do you have an opinion on the preferable path here or is there an extension point in pytest that I've missed?

**Comment by nicoddemus** [comment]
Hi @reaperhulk,

Probably it is the way it is today to mimic how `unittest` reports the same in their subtests support:

```python
import unittest


class T(unittest.TestCase):
    def test_foo(self):
        for _ in range(5):
            with self.subTest():
                assert True


if __name__ == "__main__":
    unittest.main()
```

```
λ python .tmp\test_foo.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

**Comment by nicoddemus** [comment]
As to the other question:

Seems like we can change the current implementation of `pytest_report_teststatus` to return a separate category for subtests.

https://github.com/pytest-dev/pytest/blob/c988e49af63a50f0704a46a93e73463666451af0/src/_pytest/terminal.py#L511-L522

The `category` above could be `subtests`, I think then it would create a new section in the summary automatically.

**Comment by reaperhulk** [comment]
We could definitely change it to do `subtests passed`, `subtests skipped`, `subtests failed` as additional categories, and that does appear to work (albeit with yellow text for all of them due to https://github.com/pytest-dev/pytest/blob/c988e49af63a50f0704a46a93e73463666451af0/src/_pytest/terminal.py#L1168

I'll send a PR and we can discuss there 😄
