### ISSUE TITLE
Why isn't pytest-subtests merged into pytest ?

### ISSUE THREAD

**Issue by mkmoisen** [pytest-dev/pytest-subtests#61]
Just curious as to why I need to install pytest-subtests in addition to pytest? Would it be possible to merge pytest-subtests into the main pytest module?

**Comment by RonnyPfannschmidt** [comment]
Primarily to allow experiments and to learn about detail we might miss before bringing it in with no way back

**Comment by mkmoisen** [comment]
@RonnyPfannschmidt  ok thanks.
