### ISSUE TITLE
Unit tests are failing on 0.7.0.

### ISSUE THREAD

**Issue by JuniorJPDJ** [pytest-dev/pytest-subtests#68]
Hello,
I'm the Alpine Linux package maintainer for pytest-subtestes.
After updating the package from 0.6.0 to 0.7.0 tests are failing.
It's possibly caused by other dependencies, but worth to check.

There's upgrade merge request on alpine packages repository: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/33085
Please take a look for the build pipelines - tests are run there.

I've no idea what is particural cause for this.

**Comment by RonnyPfannschmidt** [comment]
this is a dependency specification bug in pytest-subtests

@nicoddemus i beleive we either need to check the pytest version better, or add a extra pin for the argument

@JuniorJPDJ this _ispytest arg opts out of a very specific pytest warning, unfortunately it needs more recent pytest to work, it seems the dependencies dont fit

**Comment by nicoddemus** [comment]
Indeed, we need to pin for pytest>=7.

**Comment by JuniorJPDJ** [comment]
Probably as this is the latest pytest packaged in alpine linux. Thanks for the hint, I'll try updating this package and let you know guys!

**Comment by nicoddemus** [comment]
Thanks! I will close this for now, but feel free to follow up later. 👍
