### ISSUE TITLE
Output shows as yellow with no warnings

### ISSUE THREAD

**Issue by Andrew-Brock** [pytest-dev/pytest-subtests#86]
Once a subtest has been run, the output changes from green to yellow for seemingly no reason. I spent a while trying to diagnose if there were some warnings getting raised and suppressed or if there was something wrong with my usage of subtests but eventually realised that this seems to just be normal behaviour.

![image](https://user-images.githubusercontent.com/47872809/231387717-da618df8-1b36-4ea1-8c1a-7fe4b1453132.png)

The reason is that `_pytest.terminal.KNOWN_TYPES` & `_pytest.terminal._color_for_type` don't know about the `"subtests xxx"` status keys so consider them as unknown and hence show them as yellow.

Simply adding the below to the end of `pytest_subtests.py` makes the output show in the colours I'd expect it to be in. This may not be the best fix given it is reaching into the internals of pytest but it works fine.
```python
import _pytest

_pytest.terminal.KNOWN_TYPES = (
    _pytest.terminal.KNOWN_TYPES +
    tuple(f"subtests {outcome}" for outcome in ("passed", "failed", "skipped"))
)

_pytest.terminal._color_for_type.update({
    f"subtests {outcome}": _pytest.terminal._color_for_type[outcome]
     for outcome in ("passed", "failed", "skipped")
     if outcome in _pytest.terminal._color_for_type
})
```

![image](https://user-images.githubusercontent.com/47872809/231399902-2f839c43-f7ac-4329-a502-8f58a50ee8db.png)

relevant requirements
```
pytest==7.2.2
pytest-cov==4.0.0
pytest-mock==3.10.0
pytest-asyncio==0.21.0
pytest-subtests==0.10.0
```

**Comment by nicoddemus** [comment]
Thanks @Andrew-Brock!
