### ISSUE TITLE
Request: usage without context manager

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest-subtests#89]
Is it possible to have `subtests` work _without_ a context manager?  Something like `subtests.inline_test`:

```python
def test_several_cases(subtests) -> None:
    subtests.inline_test(msg="test 1"):
    assert 0 % 2 == 0

    # Upon next inline_test call,
    # the first test case is considered over
    subtests.inline_test(msg="test 2"):
    assert 1 % 2 == 1
```

Why consider this?  I find my tests losing out on a lot of whitespace.  Here's an example:
- 8 chars: test `class` and then test method `def`
- 4 chars: `patch`es
- 4 chars: `pytest.raises`
- Now we arrive at the test behavior(s), already 16+ chars indented

Adding `with subtests.test`, one loses another 4 characters.  `black` then steps in to wrap within 88-chars, and I end up with unnecessarily vertically long code blocks.

Is there any appetite to support something that doesn't require context management?

---

Workarounds:

1. Calling `__enter__` and `__exit__` manually
2. Inlining `subtests.test` with `patch`ing

**Comment by RonnyPfannschmidt** [comment]
Personally im strictly again that type of state footgun

**Comment by jamesbraza** [comment]
Haha nice use of the term footgun.  Yeah, if used incorrectly within one's tests, stuff like this can be a footgun.

I think for cut-and-dry tests (the majority of subtests) it can divide cases without requiring context management to visually interfere.

Feel free to close this out, just sharing what I thought was a decent idea

**Comment by RonnyPfannschmidt** [comment]
Thing is, you need a context to manage the stuff that needs changes, like capture, exception catching and so on

Subtests is way more than just slapping a name somewhere

In particular exception control (one of the key features is simply not safely doable without
